<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>U3DViewer.Agent.Mono</AssemblyName>
    <RootNamespace>U3DViewer.Agent.Mono</RootNamespace>
    <Version>0.1.0</Version>
    <UnityReferenceDir Condition="'$(UnityReferenceDir)' == ''">$(MSBuildProjectDirectory)\lib</UnityReferenceDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="6.0.0-be.785" />
    <PackageReference Include="BepInEx.Unity.Mono" Version="6.0.0-be.785" />
    <ProjectReference Include="..\U3DViewer.Protocol\U3DViewer.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(UnityReferenceDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.SceneManagementModule">
      <HintPath>$(UnityReferenceDir)\UnityEngine.SceneManagementModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
