<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>U3DViewer.Viewer</AssemblyName>
    <RootNamespace>U3DViewer.Viewer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <ProjectReference Include="..\U3DViewer.Protocol\U3DViewer.Protocol.csproj" />
  </ItemGroup>
</Project>
